/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersRouteImport } from './routes/users'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as MedicationoldRouteImport } from './routes/medicationold'
import { Route as MedicationRouteImport } from './routes/medication'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IntegrityRouteImport } from './routes/integrity'
import { Route as InspectionRouteImport } from './routes/inspection'
import { Route as ComplianceRouteImport } from './routes/compliance'
import { Route as CareRecordsRouteImport } from './routes/care-records'
import { Route as AuditLogsRouteImport } from './routes/audit-logs'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResidentsIndexRouteImport } from './routes/residents/index'
import { Route as ResidentsIdRouteImport } from './routes/residents/$id'

const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const MedicationoldRoute = MedicationoldRouteImport.update({
  id: '/medicationold',
  path: '/medicationold',
  getParentRoute: () => rootRouteImport,
} as any)
const MedicationRoute = MedicationRouteImport.update({
  id: '/medication',
  path: '/medication',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrityRoute = IntegrityRouteImport.update({
  id: '/integrity',
  path: '/integrity',
  getParentRoute: () => rootRouteImport,
} as any)
const InspectionRoute = InspectionRouteImport.update({
  id: '/inspection',
  path: '/inspection',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplianceRoute = ComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => rootRouteImport,
} as any)
const CareRecordsRoute = CareRecordsRouteImport.update({
  id: '/care-records',
  path: '/care-records',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditLogsRoute = AuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResidentsIndexRoute = ResidentsIndexRouteImport.update({
  id: '/residents/',
  path: '/residents/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResidentsIdRoute = ResidentsIdRouteImport.update({
  id: '/residents/$id',
  path: '/residents/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audit-logs': typeof AuditLogsRoute
  '/care-records': typeof CareRecordsRoute
  '/compliance': typeof ComplianceRoute
  '/inspection': typeof InspectionRoute
  '/integrity': typeof IntegrityRoute
  '/login': typeof LoginRoute
  '/medication': typeof MedicationRoute
  '/medicationold': typeof MedicationoldRoute
  '/settings': typeof SettingsRoute
  '/users': typeof UsersRoute
  '/residents/$id': typeof ResidentsIdRoute
  '/residents/': typeof ResidentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audit-logs': typeof AuditLogsRoute
  '/care-records': typeof CareRecordsRoute
  '/compliance': typeof ComplianceRoute
  '/inspection': typeof InspectionRoute
  '/integrity': typeof IntegrityRoute
  '/login': typeof LoginRoute
  '/medication': typeof MedicationRoute
  '/medicationold': typeof MedicationoldRoute
  '/settings': typeof SettingsRoute
  '/users': typeof UsersRoute
  '/residents/$id': typeof ResidentsIdRoute
  '/residents': typeof ResidentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audit-logs': typeof AuditLogsRoute
  '/care-records': typeof CareRecordsRoute
  '/compliance': typeof ComplianceRoute
  '/inspection': typeof InspectionRoute
  '/integrity': typeof IntegrityRoute
  '/login': typeof LoginRoute
  '/medication': typeof MedicationRoute
  '/medicationold': typeof MedicationoldRoute
  '/settings': typeof SettingsRoute
  '/users': typeof UsersRoute
  '/residents/$id': typeof ResidentsIdRoute
  '/residents/': typeof ResidentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audit-logs'
    | '/care-records'
    | '/compliance'
    | '/inspection'
    | '/integrity'
    | '/login'
    | '/medication'
    | '/medicationold'
    | '/settings'
    | '/users'
    | '/residents/$id'
    | '/residents/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audit-logs'
    | '/care-records'
    | '/compliance'
    | '/inspection'
    | '/integrity'
    | '/login'
    | '/medication'
    | '/medicationold'
    | '/settings'
    | '/users'
    | '/residents/$id'
    | '/residents'
  id:
    | '__root__'
    | '/'
    | '/audit-logs'
    | '/care-records'
    | '/compliance'
    | '/inspection'
    | '/integrity'
    | '/login'
    | '/medication'
    | '/medicationold'
    | '/settings'
    | '/users'
    | '/residents/$id'
    | '/residents/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuditLogsRoute: typeof AuditLogsRoute
  CareRecordsRoute: typeof CareRecordsRoute
  ComplianceRoute: typeof ComplianceRoute
  InspectionRoute: typeof InspectionRoute
  IntegrityRoute: typeof IntegrityRoute
  LoginRoute: typeof LoginRoute
  MedicationRoute: typeof MedicationRoute
  MedicationoldRoute: typeof MedicationoldRoute
  SettingsRoute: typeof SettingsRoute
  UsersRoute: typeof UsersRoute
  ResidentsIdRoute: typeof ResidentsIdRoute
  ResidentsIndexRoute: typeof ResidentsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medicationold': {
      id: '/medicationold'
      path: '/medicationold'
      fullPath: '/medicationold'
      preLoaderRoute: typeof MedicationoldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medication': {
      id: '/medication'
      path: '/medication'
      fullPath: '/medication'
      preLoaderRoute: typeof MedicationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrity': {
      id: '/integrity'
      path: '/integrity'
      fullPath: '/integrity'
      preLoaderRoute: typeof IntegrityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inspection': {
      id: '/inspection'
      path: '/inspection'
      fullPath: '/inspection'
      preLoaderRoute: typeof InspectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compliance': {
      id: '/compliance'
      path: '/compliance'
      fullPath: '/compliance'
      preLoaderRoute: typeof ComplianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/care-records': {
      id: '/care-records'
      path: '/care-records'
      fullPath: '/care-records'
      preLoaderRoute: typeof CareRecordsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit-logs': {
      id: '/audit-logs'
      path: '/audit-logs'
      fullPath: '/audit-logs'
      preLoaderRoute: typeof AuditLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/residents/': {
      id: '/residents/'
      path: '/residents'
      fullPath: '/residents/'
      preLoaderRoute: typeof ResidentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/residents/$id': {
      id: '/residents/$id'
      path: '/residents/$id'
      fullPath: '/residents/$id'
      preLoaderRoute: typeof ResidentsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuditLogsRoute: AuditLogsRoute,
  CareRecordsRoute: CareRecordsRoute,
  ComplianceRoute: ComplianceRoute,
  InspectionRoute: InspectionRoute,
  IntegrityRoute: IntegrityRoute,
  LoginRoute: LoginRoute,
  MedicationRoute: MedicationRoute,
  MedicationoldRoute: MedicationoldRoute,
  SettingsRoute: SettingsRoute,
  UsersRoute: UsersRoute,
  ResidentsIdRoute: ResidentsIdRoute,
  ResidentsIndexRoute: ResidentsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
